import { useState } from 'react';
import { FileText, Download, Filter, Calendar, MapPin, CheckCircle, Clock, Eye, Trash2, X, BarChart2 } from 'lucide-react';
import { useToastStore } from '../store/toastStore';
import { KPI_DATA, MONTHLY_CRIME_DATA } from '../utils/mockData';
import { motion, AnimatePresence } from 'framer-motion';
import { jsPDF } from 'jspdf';
import { useAssignedCases } from '../store/caseStore';

const MOCK_HISTORY = [
  { id: 'REP-001', title: 'Cyber Crimes Summary (June 2026)', date: 'July 1, 2026', status: 'Ready', jurisdiction: 'State-wide', category: 'Cyber Crime', timeframe: 'Last 30 Days' },
  { id: 'REP-002', title: 'Bengaluru South Hotspot Analysis', date: 'June 28, 2026', status: 'Ready', jurisdiction: 'Bengaluru Urban', category: 'All Categories', timeframe: 'Last 7 Days' },
];

const generateReportContent = (title: string, data: any) => {
  const stats = data.stats || KPI_DATA;
  return `CONFIDENTIAL INTELLIGENCE REPORT
=========================================================
Report Title: ${title}
Generated on: ${new Date().toLocaleDateString()}
Jurisdiction: ${data.jurisdiction}
Category:     ${data.category}
Timeframe:    ${data.timeframe}
=========================================================

1. EXECUTIVE SUMMARY
---------------------------------------------------------
This document contains sensitive intelligence data generated by the Rakshak-AI Pipeline. 
The analysis covers recent trends and anomalies detected within the specified jurisdiction.

2. KEY PERFORMANCE INDICATORS (KPIs)
---------------------------------------------------------
Total FIRs Logged:       ${stats.totalFirs}
Active Investigations:   ${stats.activeCases}
Solved Cases:            ${stats.solvedCases}
Identified Hotspots:     ${stats.crimeHotspots}
Repeat Offenders:        ${stats.repeatOffenders}

3. SYSTEM RECOMMENDATIONS
---------------------------------------------------------
${(stats.recommendations || [
  "- Increase patrol density in identified hotspots during peak hours (18:00 - 02:00).",
  "- Deploy specialized cyber task force for emerging financial fraud vectors.",
  `- Expedite charge sheet preparation for ${stats.pendingInvestigation} pending cases.`
]).join('\n')}

*** END OF REPORT ***`;
};

const Reports = () => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [history, setHistory] = useState(MOCK_HISTORY);
  const [previewReport, setPreviewReport] = useState<any>(null);
  const { addToast } = useToastStore();

  const [formData, setFormData] = useState({
    jurisdiction: 'State-wide (Karnataka)',
    category: 'All Categories',
    timeframe: 'Last 30 Days'
  });

  const cases = useAssignedCases();

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    setIsGenerating(true);
    
    let filteredCases = cases;
    if (formData.jurisdiction !== 'State-wide (Karnataka)') {
      const searchKey = formData.jurisdiction.split(' ')[0];
      filteredCases = cases.filter(c => c.district?.includes(searchKey) || c.jurisdiction?.includes(searchKey));
    }

    const activeCases = filteredCases.filter(c => c.status !== 'Closed').length;
    const solvedCases = filteredCases.filter(c => c.status === 'Closed').length;
    
    const now = new Date();
    const trendData = [3, 2, 1, 0].map(monthsAgo => {
      const d = new Date();
      d.setMonth(now.getMonth() - monthsAgo);
      const factor = (4 - monthsAgo) / 4;
      return {
        name: d.toLocaleString('default', { month: 'short' }),
        cyber: Math.floor((filteredCases.length * 0.4) * factor) || 0,
        theft: Math.floor((filteredCases.length * 0.3) * factor) || 0,
        assault: Math.floor((filteredCases.length * 0.3) * factor) || 0
      };
    });

    const recommendations = [
      `- Increase patrol density in ${Math.max(1, Math.floor(filteredCases.length / 4))} identified hotspots during peak hours.`,
      filteredCases.length > 5 ? `- Deploy specialized cyber task force for ${formData.jurisdiction.split(' ')[0]}.` : `- Maintain current monitoring levels for ${formData.jurisdiction.split(' ')[0]}.`,
      `- Expedite charge sheet preparation for ${activeCases} pending cases.`
    ];

    const stats = {
      totalFirs: filteredCases.length,
      activeCases: activeCases,
      solvedCases: solvedCases,
      crimeHotspots: Math.max(1, Math.floor(filteredCases.length / 4)),
      repeatOffenders: Math.floor(filteredCases.length * 1.2),
      pendingInvestigation: activeCases,
      trendData,
      recommendations
    };
    
    // Simulate generation time
    setTimeout(() => {
      setIsGenerating(false);
      addToast('Report generated successfully! Check your history.', 'success');
      const newReport = {
        id: `REP-00${history.length + 1}`,
        title: `${formData.category} Report (${formData.jurisdiction.split(' ')[0]})`,
        date: new Date().toLocaleDateString(),
        status: 'Ready',
        jurisdiction: formData.jurisdiction,
        category: formData.category,
        timeframe: formData.timeframe,
        stats: stats
      };
      setHistory([newReport, ...history]);
    }, 2000);
  };

  const handleDownload = (report: any) => {
    addToast(`Generating PDF for ${report.title}...`, 'info');
    
    setTimeout(() => {
      try {
        const doc = new jsPDF();
        
        // Add logo/header background
        doc.setFillColor(15, 23, 42); // Dark blue/slate header
        doc.rect(0, 0, 210, 40, 'F');
        
        // Header Text
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text("RAKSHAK-AI INTELLIGENCE REPORT", 105, 20, { align: "center" });
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.text("CONFIDENTIAL - FOR AUTHORIZED PERSONNEL ONLY", 105, 30, { align: "center" });
        
        // Meta data
        doc.setTextColor(30, 41, 59); // Slate 800
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("Report Title:", 20, 50);
        doc.setFont("helvetica", "normal");
        doc.text(report.title, 55, 50);
        
        doc.setFont("helvetica", "bold");
        doc.text("Generated On:", 20, 60);
        doc.setFont("helvetica", "normal");
        doc.text(new Date().toLocaleDateString(), 55, 60);
        
        doc.setFont("helvetica", "bold");
        doc.text("Jurisdiction:", 20, 70);
        doc.setFont("helvetica", "normal");
        doc.text(report.jurisdiction, 55, 70);
        
        doc.setFont("helvetica", "bold");
        doc.text("Category:", 120, 60);
        doc.setFont("helvetica", "normal");
        doc.text(report.category, 145, 60);
        
        doc.setFont("helvetica", "bold");
        doc.text("Timeframe:", 120, 70);
        doc.setFont("helvetica", "normal");
        doc.text(report.timeframe, 145, 70);
        
        // Divider
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 75, 190, 75);
        
        // Summary
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(15, 23, 42);
        doc.text("1. Executive Summary", 20, 85);
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const summaryText = "This document contains sensitive intelligence data generated by the Rakshak-AI Pipeline. The analysis covers recent trends and anomalies detected within the specified jurisdiction based on active FIRs and intelligence feeds.";
        const splitSummary = doc.splitTextToSize(summaryText, 170);
        doc.text(splitSummary, 20, 92);
        
        // KPIs
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("2. Key Performance Indicators", 20, 110);
        const stats = report.stats || KPI_DATA;
        
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        
        doc.text(`Total FIRs Logged:`, 20, 120);
        doc.text(`${stats.totalFirs.toLocaleString()}`, 65, 120);
        
        doc.text(`Active Investigations:`, 20, 128);
        doc.text(`${stats.activeCases.toLocaleString()}`, 65, 128);
        
        doc.text(`Solved Cases:`, 20, 136);
        doc.text(`${stats.solvedCases.toLocaleString()}`, 65, 136);
        
        doc.text(`Identified Hotspots:`, 110, 120);
        doc.text(`${stats.crimeHotspots}`, 155, 120);
        
        doc.text(`Repeat Offenders:`, 110, 128);
        doc.text(`${stats.repeatOffenders.toLocaleString()}`, 155, 128);
        
        // System Recommendations
        let yPos = 150;
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("3. System Recommendations", 20, yPos);
        
        yPos += 8;
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const recs = stats.recommendations || [
          "- Increase patrol density in identified hotspots during peak hours (18:00 - 02:00).",
          "- Deploy specialized cyber task force for emerging financial fraud vectors.",
          `- Expedite charge sheet preparation for ${stats.pendingInvestigation} pending cases nearing the 90-day deadline.`
        ];
        
        recs.forEach((rec: string) => {
          const splitRec = doc.splitTextToSize(rec, 170);
          doc.text(splitRec, 20, yPos);
          yPos += splitRec.length * 6;
        });
        
        // Footer
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // Slate 400
        doc.text("*** END OF REPORT ***", 105, 280, { align: "center" });
        doc.text(`Rakshak-AI Automated Intelligence System - ID: ${report.id}`, 105, 285, { align: "center" });

        // Download
        doc.save(`${report.title.replace(/ /g, '_')}.pdf`);
        addToast('PDF downloaded successfully', 'success');
      } catch (err) {
        console.error("PDF Generation Error", err);
        addToast('Error generating PDF', 'error');
      }
    }, 800);
  };

  const handleDelete = (id: string) => {
    setHistory(history.filter(h => h.id !== id));
    addToast('Report removed from history', 'info');
  };

  return (
    <div className="space-y-6 h-full flex flex-col relative">
      <div className="flex justify-between items-center border-b border-white/10 pb-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-100 flex items-center">
            <FileText className="mr-2 text-primary" /> Reports & Analytics Engine
          </h2>
          <p className="text-sm text-gray-400 mt-1">Generate comprehensive intelligence reports and audits.</p>
        </div>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1">
        <div className="lg:col-span-1 space-y-6">
          <div className="glass p-6 rounded-xl border border-white/10 relative overflow-hidden">
            {/* Background Glow */}
            <div className="absolute top-0 right-0 w-32 h-32 bg-primary/10 rounded-full blur-3xl pointer-events-none"></div>
            
            <h3 className="text-lg font-bold text-gray-200 mb-6 flex items-center">
              <Filter className="w-5 h-5 mr-2 text-primary" /> Custom Generator
            </h3>
            
            <form onSubmit={handleGenerate} className="space-y-5 relative z-10">
              <div>
                <label className="block text-xs font-semibold text-gray-400 mb-2 uppercase tracking-wider">Jurisdiction</label>
                <div className="relative">
                  <MapPin className="absolute left-3 top-2.5 h-4 w-4 text-gray-500" />
                  <select 
                    value={formData.jurisdiction}
                    onChange={(e) => setFormData({...formData, jurisdiction: e.target.value})}
                    className="w-full bg-white dark:bg-black/50 border border-gray-200 dark:border-white/10 rounded-lg pl-10 pr-4 py-2.5 text-sm text-gray-900 dark:text-white focus:outline-none focus:border-primary appearance-none cursor-pointer transition-colors"
                  >
                    <option>State-wide (Karnataka)</option>
                    <option>Bengaluru Urban</option>
                    <option>Mysuru</option>
                    <option>Hubballi-Dharwad</option>
                  </select>
                </div>
              </div>
              
              <div>
                <label className="block text-xs font-semibold text-gray-400 mb-2 uppercase tracking-wider">Crime Category</label>
                <div className="relative">
                  <BarChart2 className="absolute left-3 top-2.5 h-4 w-4 text-gray-500" />
                  <select 
                    value={formData.category}
                    onChange={(e) => setFormData({...formData, category: e.target.value})}
                    className="w-full bg-white dark:bg-black/50 border border-gray-200 dark:border-white/10 rounded-lg pl-10 pr-4 py-2.5 text-sm text-gray-900 dark:text-white focus:outline-none focus:border-primary appearance-none cursor-pointer transition-colors"
                  >
                    <option>All Categories</option>
                    <option>Cyber Crime</option>
                    <option>Financial Fraud</option>
                    <option>Heinous Crimes</option>
                    <option>Facial Intelligence Report</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-gray-400 mb-2 uppercase tracking-wider">Timeframe</label>
                <div className="relative">
                  <Calendar className="absolute left-3 top-2.5 h-4 w-4 text-gray-500" />
                  <select 
                    value={formData.timeframe}
                    onChange={(e) => setFormData({...formData, timeframe: e.target.value})}
                    className="w-full bg-white dark:bg-black/50 border border-gray-200 dark:border-white/10 rounded-lg pl-10 pr-4 py-2.5 text-sm text-gray-900 dark:text-white focus:outline-none focus:border-primary appearance-none cursor-pointer transition-colors"
                  >
                    <option>Last 7 Days</option>
                    <option>Last 30 Days</option>
                    <option>Year to Date</option>
                    <option>Custom Range</option>
                  </select>
                </div>
              </div>

              <div className="pt-2">
                <button 
                  type="submit"
                  disabled={isGenerating}
                  className={`w-full py-3 rounded-lg font-bold flex items-center justify-center transition-all ${
                    isGenerating ? 'bg-primary/30 text-gray-400 cursor-not-allowed border border-primary/20' : 'bg-primary hover:bg-blue-600 text-white shadow-lg shadow-primary/25 border border-transparent'
                  }`}
                >
                  {isGenerating ? (
                    <><Clock className="w-5 h-5 mr-2 animate-spin" /> Compiling Intel...</>
                  ) : (
                    <><FileText className="w-5 h-5 mr-2" /> Generate Report</>
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>

        <div className="lg:col-span-2">
          <div className="glass p-6 rounded-xl border border-white/10 h-full flex flex-col">
            <h3 className="text-lg font-bold text-gray-200 mb-6 flex items-center">
              <Download className="w-5 h-5 mr-2 text-primary" /> Report Archive
            </h3>
            
            <div className="space-y-3 overflow-y-auto flex-1 pr-2">
              <AnimatePresence>
                {history.length > 0 ? (
                  history.map((rep, index) => (
                    <motion.div 
                      key={rep.id}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, scale: 0.95 }}
                      transition={{ delay: index * 0.05 }}
                      className="bg-black/40 border border-white/10 p-4 rounded-xl flex items-center justify-between hover:bg-white/5 transition-all group"
                    >
                      <div className="flex items-center">
                        <div className="bg-success/20 p-2.5 rounded-lg mr-4 border border-success/30">
                          <CheckCircle className="w-5 h-5 text-success" />
                        </div>
                        <div>
                          <h4 className="font-bold text-gray-200 text-sm md:text-base">{rep.title}</h4>
                          <p className="text-xs text-gray-500 mt-1">{rep.id} • Generated: {rep.date} • {rep.timeframe}</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 opacity-80 group-hover:opacity-100 transition-opacity">
                        <button 
                          onClick={() => setPreviewReport(rep)} 
                          className="p-2 bg-white/5 hover:bg-primary/20 rounded-lg text-gray-400 hover:text-primary transition-colors tooltip-trigger"
                          title="Preview Report"
                        >
                          <Eye className="w-4 h-4" />
                        </button>
                        <button 
                          onClick={() => handleDownload(rep)} 
                          className="p-2 bg-white/5 hover:bg-primary/20 rounded-lg text-gray-400 hover:text-primary transition-colors"
                          title="Download PDF"
                        >
                          <Download className="w-4 h-4" />
                        </button>
                        <button 
                          onClick={() => handleDelete(rep.id)} 
                          className="p-2 bg-white/5 hover:bg-red-500/20 rounded-lg text-gray-400 hover:text-red-400 transition-colors"
                          title="Delete Report"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </motion.div>
                  ))
                ) : (
                  <div className="flex flex-col items-center justify-center h-48 text-gray-500">
                    <FileText className="w-12 h-12 mb-3 opacity-20" />
                    <p>No reports generated yet.</p>
                  </div>
                )}
              </AnimatePresence>
            </div>
          </div>
        </div>
      </div>

      {/* Preview Modal */}
      <AnimatePresence>
        {previewReport && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
          >
            <motion.div 
              initial={{ scale: 0.95, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.95, y: 20 }}
              className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-white/20 rounded-xl max-w-3xl w-full max-h-[85vh] flex flex-col shadow-2xl overflow-hidden"
            >
              <div className="flex justify-between items-center p-4 border-b border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-black/50">
                <h3 className="text-lg font-bold text-gray-900 dark:text-white flex items-center">
                  <Eye className="mr-2 w-5 h-5 text-primary" /> Report Preview: {previewReport.id}
                </h3>
                <div className="flex gap-2">
                  <button 
                    onClick={() => handleDownload(previewReport)}
                    className="flex items-center gap-2 px-3 py-1.5 bg-primary/10 hover:bg-primary/20 dark:bg-primary/20 dark:hover:bg-primary text-primary dark:hover:text-white rounded text-sm transition-colors"
                  >
                    <Download className="w-4 h-4" /> Download PDF
                  </button>
                  <button 
                    onClick={() => setPreviewReport(null)}
                    className="p-1.5 bg-gray-200 hover:bg-gray-300 dark:bg-white/10 dark:hover:bg-white/20 text-gray-600 dark:text-gray-300 rounded transition-colors"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>
              </div>
              
              <div className="p-6 overflow-y-auto bg-gray-100 dark:bg-black/20">
                <pre className="font-mono text-sm text-gray-800 dark:text-gray-300 whitespace-pre-wrap leading-relaxed">
                  {generateReportContent(previewReport.title, previewReport)}
                </pre>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default Reports;
